=== zaq3102/Algo/java_basic/src/com/ssafy/day6/xml/student.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ssafy (student*)>
<!ELEMENT student (name, loc, phone?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT loc (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST student no CDATA "0">

=== zaq3102/Algo/java_basic/bin/com/ssafy/day6/xml/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ssafy SYSTEM "./student.dtd">
<ssafy>
	<student no="12345">
		<name>홍길동</name>
		<loc>광주</loc>
		<phone>010-222-3333</phone>
	</student>

	<student no="23456">
		<name>장길산</name>
		<loc>서울</loc>
		<phone>010-333-4444</phone>
	</student>

	<student no="34567">
		<name>임꺽정</name>
		<loc>대전</loc>
	</student>
</ssafy>
